
name: test

run-name: ${{ github.actor }} Deploy WebSite to GitHub Pages 🚀

on:
  push: 
    branches:
    - test
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date 
        id: alist_version
        run: echo "::set-output name=version::$(curl -s  https://api.github.com/repos/alist-org/alist/releases/latest | grep tag_name | cut -f4 -d '\"')" 

      - name: echo version
        run: echo ${{ steps.alist_version.outputs.version }}

