
name: test

run-name: ${{ github.actor }} Deploy WebSite to GitHub Pages 🚀

on:
  push: 
    branches:
    - test
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get alist version
        id: alist_version
        run: |
          echo "alist_version=$(curl -s  https://api.github.com/repos/alist-org/alist/releases/latest | grep tag_name | cut -f4 -d '"')" >> "$GITHUB_ENV"
      
      # - name: Get current date 
      #   id: alist_version
      #   run: echo "::set-output name=version::$(curl -s  https://api.github.com/repos/alist-org/alist/releases/latest | grep tag_name | cut -f4 -d '\"')" 
      #   run: echo "::set-output name={name}::{value}"
        
      - name: echo version
        run: echo "version ${alist_version}"


