
name: test

run-name: ${{ github.actor }} Deploy WebSite to GitHub Pages 🚀

on:
  push: 
    branches:
    - test
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      alist_version: xxxxx123
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get alist version
        id: alist_version
        run: |
          echo "alist_version=$(curl -s  https://api.github.com/repos/alist-org/alist/releases/latest | grep tag_name | cut -f4 -d '"')" >> "$GITHUB_ENV"
        
      - name: echo version
        run: echo "version ${alist_version}"

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: echo version test
        run: echo "version ${alist_version}"
